- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - zsh
      - tmux
      - nvm
      - vim
      - git
      - ag
      - go
      - jq
      - peco
      - wget
      - tree
      - direnv
      - ngrok
      - cmake
      - curlish
      - rbenv-default-gems
      - heroku-toolbelt
      - jpeg
      - libpng
      - imagemagick
      - reattach-to-user-namespace
      - readline
      - openssl
      - { name: openssl, state: linked, install_options: force }

    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - alfred
      - dash
      - dropbox
      - atom
      - coteditor
      - github
      - skype
      - iterm2
      - firefox
      - macvim
      - itsycal
      - mplayerx
      - mailplane
      - silverlight
      - gyazo
      - boot2docker
      - vagrant
      - audacity
      - transmit
      - handbrake
      - appcleaner
      - lingrradar
      - adobe-air
      - firefox-ja
      - slack
      - virtualbox
